version: '3'
services:
   python3:
     build:
       context: .
       args:
         UID: $UID
         GID: $GID
     container_name: 'python3_house_local'
     restart: always
     working_dir: '/opt/working'
     tty: true
     volumes:
        - ./working:/opt/working
     ports:
        - 5555:5555
